set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv)
set(tools /home/vagrant/chipyard/riscv-tools-install)
set(CMAKE_C_COMPILER ${tools}/bin/riscv64-unknown-elf-gcc CACHE STRING "C compiler" FORCE)
set(CMAKE_CXX_COMPILER ${tools}/bin/riscv64-unknown-elf-g++ CACHE STRING "C++ compiler" FORCE)
set(CMAKE_FIND_ROOT_PATH ${tools}/riscv64-unknown-elf)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
